src/main/java/com/cars/platform/domain/Person.java
package com.cars.platform.domain;

import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.TypedQuery;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

@RooJavaBean
@RooToString
@RooJpaActiveRecord(finders = { "findPeopleByUsernameEquals", "findPeopleByCompany", "findPeopleByPersonRole" })
public class Person {

    private String firstName;
    private String lastName;
    private String email;
    private String title;
    private String password;
    @ManyToOne
    private Company company;
    @Enumerated
    private PersonRole personRole = PersonRole.BASIC;

    private String username;
    private String phone;
    private String passwordResetCode;
    private boolean enabled = true;

    private boolean publicContact;
    private boolean emailRemindersEnabled;
    private boolean emailUploadRemindersEnabled;
    private boolean newFinancialRemindersEnabled;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "M-")
    private Date agreementDate;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "M-")
    private Date agreementDateSelect;

    public boolean isAdmin() {
	return PersonRole.ADMIN.equals(personRole);
    }

    public boolean isAnalyst() {
	return ((company != null) && (CompanyType.CARS.equals(company.getCompanyType())));
    }

    public boolean isSubscriber() {
	return ((company != null) && (CompanyType.INVESTOR.equals(company.getCompanyType())));
    }

    public String getFullName() {
	String fullName = "";
	if (firstName != null) {
	    fullName += firstName;
	}
	fullName += " ";
	if (lastName != null) {
	    fullName += lastName;
	}
	return fullName;
    }

    public static List<Person> findAnalysts() {
	TypedQuery<Person> q = entityManager().createQuery("SELECT o FROM Person o where o.company.companyType = :companyType and o.personRole = :personRole", Person.class);
	q.setParameter("companyType", CompanyType.CARS);
	q.setParameter("personRole", PersonRole.BASIC);

	return q.getResultList();
    }

    public static boolean isUsernameInUse(String username) {
	boolean inUse = false;
	try {

	    Person person = Person.findPeopleByUsernameEquals(username);
	    if (null != person) {
		    inUse = true;
	    }
	} catch (Exception ignore) {
	}
	return inUse;
    }


	public static Person findPeopleByUsernameEquals(String username) {
        if (username == null || username.length() == 0) throw new IllegalArgumentException("The username argument is required");
        EntityManager em = Person.entityManager();
        TypedQuery<Person> q = em.createQuery("SELECT o FROM Person AS o WHERE o.username = :username", Person.class);
        q.setParameter("username", username);
        return q.getSingleResult();
    }
}

src/main/webapp/WEB-INF/views/peergroupslist.jspx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div xmlns:field="urn:jsptagdir:/WEB-INF/tags/form/fields"
	xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:spring="http://www.springframework.org/tags"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:tiles="http://tiles.apache.org/tags-tiles"
	xmlns:fmt="http://java.sun.com/jsp/jstl/fmt"
	xmlns:sform="http://www.springframework.org/tags/form"
	xmlns:page="urn:jsptagdir:/WEB-INF/tags/form" version="2.0">
	<jsp:directive.page contentType="text/html;charset=UTF-8" />
	<jsp:output omit-xml-declaration="yes" />
	
	<!-- not inherited from enclosing jspx? --> 
	<spring:url var="peerGroups" value="/peergroups"></spring:url>
	
	<spring:url var="myCdfis" value="/investor/${company.id }/myreports" />
	
	<spring:url var="accordion" value="/lib/accordion.js" />
	<script type="text/javascript" src="${accordion}"><!-- required for FF3 and Opera --></script>
	
<style>
.ui-accordion .ui-accordion-header {
	background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    border: 0 none;
    font-size: small;
    height: 12px;
}

.ui-accordion .ui-accordion-content {
	font-size: 12px;
	padding: 10px 5px;
	background:none;
	border:0px;
}

.ui-state-hover {
	color:#000;
}

.ui-state-default {
	background:none;
}

h4 span {
	float: left !important;
	height: 20px !important;
}
</style>


<c:set var="inCDFI" value="false" />
<c:if test="${company.CDFI}">
	<c:set var="inCDFI" value="true" />
</c:if> 

<c:set var="personIsCDFI" value="false" />
<c:if test="${person.company.CDFI}">
	<c:set var="personIsCDFI" value="true" />
</c:if> 

<c:set var="personIsAnalyst" value="false" />
<c:if test="${person.company.CARS &amp;&amp; !person.admin}">
	<c:set var="personIsAnalyst" value="true" />
</c:if> 

<!--  TODO don't allow this for subscribers unless they have ALL?
      see same comment in cdfi/peergrouplist.jspx-->
<c:set var="canEdit" value="true" />
<c:if test="${personIsAnalyst || personIsCDFI}">
	<c:set var="canEdit" value="false" />
</c:if> 

	<script>
		<![CDATA[
		         
		function AppViewModel() {
			
			local = this;
			local.peerGroups = ko.observableArray([]);
			
			/* JSON CALLS */
			
		   
			$.ajax({
				url : url,
				dataType : 'json',
				async : false,
				cache: false,
				success : function(data) {
					ko.mapping.fromJS(data, {}, local.peerGroups);
				}
			});
			
			local.removePeerGroup = function(peerGroup) {
				$("#dialog-confirm").dialog({
					resizable : false,
					height : 190,
					modal : true,
					buttons : {
						"Delete" : function() {
							$(this).dialog("close");
							$.ajax({
								url : "${peerGroups}/"+peerGroup.id(),
								type : "delete",
								contentType : "application/json",
								data: "{}",
								success : function(result) {
									local.peerGroups.remove(peerGroup)
								},
								error : function(result) {
									alert('Remove Failed');
								}
							});
	
						},
						Cancel : function() {
							$(this).dialog("close");
						}
					}
				});
			};
					
			local.getReportUrl = function(peerGroup) {
				return peerGroupReportUrl+peerGroup.id()
			};	
			
			local.createPeerGroup = ko.computed(function() {
				return createPeerGroupUrl;
			});
		}

		$(function() {
			$("#peersColumn").css("min-width", "350px");
			$("#peersList").css("min-width", "300px");
			
			if ($("#carsside").width() > 0) {
				$("#peersColumn").css("width", "250px");
				$("#peersList").css("width", "200px");
				$("#divContainer").css("max-width", "720px");
			}
			
			var vm = new AppViewModel();
			ko.applyBindings(vm);
			$('.accordion').togglepanels({"active": [-1]});
			
			$('.accordionTitle').text("Click to Show");
			$('.accordionTitle').click(function() {				
				var text = $(this).text();
				var title = text == "Click to Show" ? "Click to Hide" : "Click to Show";
				$(this).text(title);
			});
			$(".ui-icon-triangle-1-e").addClass("custom-ui-state-hover");
			$("#dialog-confirm").dialog({
				resizable : false,
				height : 190,
				modal : true,
				buttons : [{
					"text":"Cancel",
					"class":"cancel-button",
					"click" : function() {
						$(this).dialog("close");
					}
				},{
					"class":"greenButton",
					"text":"Delete",
					"click": function() {
						$(this).dialog("close");
					}
				}]
			});

			$("#dialog-confirm").dialog("close");
			

		});
		
		
		]]>
	</script>

	<div id="divContainer">

	<spring:url var="icon_blank" value="/resources/images/icon_blank.png" />

<!--
	<spring:url var="delete_image" value="/resources/images/icon_delete.png" />
	<spring:url var="delete" value="/cdfi/ratings/" />
-->


	<div data-bind="if: peerGroups().length==0">
 		<p>
        <c:choose>
	        <c:when test="${peerGroupAccess != 'FULL'}">
		        <i>Aeris has not created a peer group for this CDFI yet.</i>
		    </c:when>
			<c:otherwise>
		        <c:choose>
			        <c:when test="${inCDFI==true}">
				        <i>You have not created any peer groups for this CDFI yet.</i>
				    </c:when>
				    <c:otherwise>
				        <i>You have not created any global peer groups yet.</i>
				    </c:otherwise>
			 	</c:choose>
			</c:otherwise>
		</c:choose>
		</p>
	    <br />
	    
	    <c:if test="${peerGroupAccess == 'FULL'}">
			<a data-bind="attr: { 'href': createPeerGroup}">Create a new Peer Group</a>
			<br />
		</c:if>
    </div>

	<div data-bind="if: peerGroups().length>0">
       <c:choose>
	        <c:when test="${peerGroupAccess != 'FULL'}">
			    <p>Aeris has created the following peer groups for you to view.</p>
			</c:when>
			<c:otherwise>
				<c:choose>
					 <c:when test="${inCDFI==true}">
						<p> The following list shows the peer groups created for this CDFI.
						Click on the name to view the report for the peers listed.
						Once in that report you can update the list of peers if desired.</p>
					</c:when>
					<c:otherwise>
						<c:choose>
							<c:when test="${person.company.CARS }">					
								<p> The following list shows all of the global peer groups that Aeris has created. 
								When an investor with an All subscription with peer groups enabled first access their
								cloud they will have access to a copy of these as their initial list. 
								Click on the name to view the report for the peers listed.
								Once in that report you can update the list of peers if desired.
								</p>
							</c:when>
							<c:otherwise>
								<p> The following list shows sector peer groups available to you. 
								Click on the name to view the performance trends for that group. 
								Go to <a href="${myCdfis }">My CDFIs</a> to download a narrative Aeris Explorer Report™ for each sector peer group.
								</p>
							</c:otherwise>
						</c:choose>
					</c:otherwise>
				</c:choose>
			</c:otherwise>
		</c:choose>
	
	
	    <c:if test="${peerGroupAccess == 'FULL'}">
		    <br />			
		    <a data-bind="attr: { 'href': createPeerGroup}">Create a new Peer Group</a>
	    <br />
	    </c:if>
	    <br />
	    	    
		<table class="sort">
			<thead>
				<tr>
					<th>Name</th>
					<th>Last Saved</th>
					<th>Peers</th>
					<c:if test="${peerGroupAccess == 'FULL'}">
						<th></th>
					</c:if>
				</tr>
			</thead>
			<tbody data-bind="foreach: { data: peerGroups, as: 'peerGroup' }" >
				<tr>
				<!-- 
					<td data-bind="text:name"></td>
				 -->
					<td>
					    <a data-bind="text: name, attr: { 'href': $root.getReportUrl($data)}"></a>
					</td>					
					<td style="width:80px;" data-bind="text:updated"></td>
  					<td id="peersColumn">
  						<div class="accordion">
	  						<h4><span class="accordionTitle"><!-- Empty --></span></h4>
					        <ul id="peersList" data-bind="foreach: { data: peerGroup.peers, as: 'peer' }" style="list-style-type:none; margin-left:20px; font-size:small; float:left;" >
					            <li style="margin:0; padding:0">
					                <span data-bind="text: peer.name"><!-- empty --></span>
					            </li>
					        </ul>
				        </div>
				    </td>
				    
					<c:if test="${peerGroupAccess == 'FULL'}">
						<td style="text-align:center;">				     
	                        <span id="icon-delete"><img src="${icon_blank }" data-bind="click: $root.removePeerGroup.bind($root)" title="Remove"></img></span>				
						</td>
					</c:if>
				</tr>
			</tbody>
		</table>
	</div>


	</div>
		<div id="dialog-confirm" title="Delete Peer Group?">
		<p>
			<span class="ui-icon gui-icon-alert"
					style="float: left; margin: 0 7px 20px 0;"> <!-- EMPTY -->
			</span>Are you sure you want to delete this peer group?
		</p>
	</div>
</div>